### ISSUE TITLE
Set up a mechanism for code review

### ISSUE THREAD

**Issue by jeremiah** [Pelagicore/MainLoop#3]
Will test gerrithub.

**Comment by Gagi2k** [comment]
interesting i didn't know that.

The question would be whether gerrit makes sense without a jenkins server as well which tests the build

**Comment by jeremiah** [comment]
I agree that Gerrit should likely be part of an automated workflow. I'm not certain that GerritHub is so useful after some quick and dirty testing, its just Gerrit. Have to see how it can be linked to Jenkins.

**Comment by jeremiah** [comment]
Currently using Jenkins, closing.
